package model.enums;


public enum Flag {
    FLAG_PORTA_ABERTA,
    FLAG_SALVOU_DAVI,
    FLAG_ABANDONOU_DAVI,
    FLAG_AJOELHOU,
    FLAG_GRITOU_NOME,
    FLAG_OUVIU_RADIO,
    FLAG_DEIXOU_ANTONIO,
    FLAG_PEGOU_MEDALHA,
    FLAG_ACENDEU_VELA,
    FLAG_PROMETEU_VOLTAR
}